Make sure we insert keys properly, remove any autogenerated ones

diff --git a/jobs/pdns/templates/post-start.erb b/jobs/pdns/templates/post-start.erb
--- a/jobs/pdns/templates/post-start.erb
+++ b/jobs/pdns/templates/post-start.erb
@@ -5,17 +5,29 @@ JOB_NAME=pdns
 JOB_DIR="/var/vcap/jobs/$JOB_NAME"
 PACKAGE_DIR="/var/vcap/packages/$JOB_NAME"
 
-export PATH="${PATH}:${PACKAGE_DIR}"
+export PATH="${PATH}:${PACKAGE_DIR}/bin"
 
 <% p("dnssec.zones").each do |zone| %>
-pdnsutil --config-dir="$JOB_DIR/etc" secure-zone "<%= zone %>"
-<% end %>
+# Secure the zone
+pdnsutil --config-dir="$JOB_DIR/etc" secure-zone "<%= zone["zone"] %>" || true
 
-<% p("dnssec.keys").each do |key| %>
+# Make sure we're inserting our own keys into the zone if provided
+<% zone["keys"].each do |key| %>
 keyfile=$(mktemp)
 cat > "${keyfile}" << EOF
 <%= key["key"] %>
 EOF
-pdnsutil import-zone-key "<%= key["zone"] %>" "${keyfile}" "<%= key["active"] %>" "<%= key["type"] %>"
+pdnsutil --config-dir="$JOB_DIR/etc" import-zone-key "<%= zone["zone"] %>" "${keyfile}" "<%= key["active"] %>" "<%= key["type"] %>"
 rm "${keyfile}"
-<% done %>
+<% end %>
+
+# If we provide keys, remove stock CSK generated during secure-zone if exists
+<% if zone["keys"].length %>
+CSK_ID=$(pdnsutil --config-dir="$JOB_DIR/etc" list-keys | grep CSK | awk '{print $5'})
+pdnsutil --config-dir="$JOB_DIR/etc" remove-zone-key "<%= zone["zone"] %>" "$CSK_ID" || true
+<% end %>
+
+# clean up any changes that might affect the DNSSEC signatures
+pdnsutil --config-dir="$JOB_DIR/etc" rectify-zone "<%= zone["zone"] %>"
+
+<% end %>
